- lib/configfiles/rhel7.inc.php
- lib/configfiles_index.inc.php
- templates/misc/configfiles/rhel7/cron/etc_cron.d_froxlor
- templates/misc/configfiles/rhel7/dovecot/etc_dovecot_conf.d_10-auth.conf
- templates/misc/configfiles/rhel7/dovecot/etc_dovecot_conf.d_10-logging.conf
- templates/misc/configfiles/rhel7/dovecot/etc_dovecot_conf.d_10-mail.conf
- templates/misc/configfiles/rhel7/dovecot/etc_dovecot_conf.d_10-master.conf
- templates/misc/configfiles/rhel7/dovecot/etc_dovecot_conf.d_10-ssl.conf
- templates/misc/configfiles/rhel7/dovecot/etc_dovecot_conf.d_15-lda.conf
- templates/misc/configfiles/rhel7/dovecot/etc_dovecot_conf.d_15-mailboxes.conf
- templates/misc/configfiles/rhel7/dovecot/etc_dovecot_conf.d_20-imap.conf
- templates/misc/configfiles/rhel7/dovecot/etc_dovecot_conf.d_20-lmtp.conf
- templates/misc/configfiles/rhel7/dovecot/etc_dovecot_conf.d_20-managesieve.conf
- templates/misc/configfiles/rhel7/dovecot/etc_dovecot_conf.d_20-pop3.conf
- templates/misc/configfiles/rhel7/dovecot/etc_dovecot_conf.d_90-sieve.conf
- templates/misc/configfiles/rhel7/dovecot/etc_dovecot_dovecot-sql.conf.ext
- templates/misc/configfiles/rhel7/dovecot/etc_dovecot_dovecot.conf
- templates/misc/configfiles/rhel7/postfix/etc_postfix_main.cf
- templates/misc/configfiles/rhel7/postfix/etc_postfix_master.cf
- templates/misc/configfiles/rhel7/postfix/etc_postfix_mysql-virtual_alias_maps.cf
- templates/misc/configfiles/rhel7/postfix/etc_postfix_mysql-virtual_mailbox_domains.cf
- templates/misc/configfiles/rhel7/postfix/etc_postfix_mysql-virtual_mailbox_maps.cf
- templates/misc/configfiles/rhel7/postfix/etc_postfix_mysql-virtual_sender_permissions.cf
- templates/misc/configfiles/rhel7/proftpd/etc_proftpd_proftpd.conf
I created a basic config files set for RedHat Enterprise Linux 7 / CentOS 7.
it includes a working configuration for Froxlor with Apache 2.4, Postfix 2.10, Dovecot 2.2, ProFTPd 1.3 and AWstats
> Added RHEL 7 configfiles

- lib/configfiles/freebsd.inc.php
- templates/misc/configfiles/freebsd/pure-ftpd/usr_local_etc_pure-ftpd.conf
- templates/misc/configfiles/freebsd/pure-ftpd/usr_local_etc_pureftpd-mysql.conf
> Pure-FTPd template for FreeBSD

- lib/classes/database/class.Database.php
Add a way to set custom ports for the database.
See: http://forum.froxlor.org/index.php/topic/12989-mysql-custom-port/#entry29603
> Add custom port to userdata.inc.php

- lib/functions/filedir/function.findDirs.php
instead of stoping after first unreadable directory in function.findDirs, ignore and continue.
This Fix comes from php.net-user "antennen" @
http://php.net/manual/en/class.recursivedirectoryiterator.php#101654
> Fix Regression from commit 687c5ce for Bug #611:

- lib/configfiles/jessie.xml
Fixing permission problems with files, which have 0640 as file attributes.
Fixing problems in main.cf (Postfix). setgid_group must be set, otherwise running newaliases will fail.
Moreover I set the missing paths correctly in the main.cf (regard to Debian Jessie).
> Fixing some (big) peanuts

- admin_customers.php
It prevents possible duplication in list.
> Checking froxlor-local user membership in ftp-group

- index.php
- install/lib/class.FroxlorInstall.php
- lib/classes/bulk/class.DomainBulkAction.php
- lib/classes/idna/class.idna_convert.php
- lib/classes/webserver/class.ConfigIO.php
- lib/configfiles/jessie.xml
- lib/configfiles/precise.xml
- lib/configfiles/trusty.xml
- lib/configfiles/wheezy.xml
- lib/cron_init.php
> Fix typos found by codespell

- templates/Sparkle/assets/js/circular.js
* Remove unneeded semicolon.
* Add missing semicolon.
* Add linefeed at end of file
> templates: Code cleanup

- customer_extras.php
- scripts/jobs/cron_tasks.inc.http.10.apache.php
this contributes to the suexec workaround
it fixes symlink ownership and adds removing of cgi-bin folder and symlink to removal of dir options
> improvements of suexec-workaround

- lib/classes/phpinterface/class.phpinterface_fpm.php
see https://suhosin.org/stories/howtos.html and https://suhosin.org/stories/configuration.html
> added more php_value and php_flag for suhosin

- admin_apcuinfo.php
- lib/navigation/00.froxlor.main.php
- lng/english.lng.php
- templates/Sparkle/admin/settings/apcuinfo/img_line.tpl
- templates/Sparkle/admin/settings/apcuinfo/runtime_line.tpl
- templates/Sparkle/admin/settings/apcuinfo/showinfo.tpl
- templates/Sparkle/assets/css/main.css
Added an APCu info page to Server menu with clear cache function.
Based on https://github.com/krakjoe/apcu/blob/master/apc.php
Vertical image bars changed to horizontal.
> APCu Info page

- README.md
> README: Update supported Debian versions

- lib/classes/integrity/class.IntegrityCheck.php
- lng/english.lng.php
- lng/german.lng.php
- add missing message for let's encrypt integrity check
- small spellfixes
> language: add message/spelling

- admin_domains.php
- customer_domains.php
- install/froxlor.sql
- install/updates/froxlor/0.9/update_0.9.inc.php
- lib/formfields/admin/domains/formfield.domains_add.php
- lib/formfields/admin/domains/formfield.domains_edit.php
- lib/version.inc.php
- lng/english.lng.php
- lng/german.lng.php
- templates/Sparkle/admin/domains/domains_domain.tpl
- templates/Sparkle/assets/css/main.css
- templates/Sparkle/customer/domains/domains_domain.tpl
Similar to the registration you can now enter a termination date. Until the termination date the domains are highlighted in yellow in the domain overview, then red.
> Added termination-date to domains

- scripts/jobs/cron_tasks.inc.dns.10.bind.php
cron_tasks/bind: refactor zone creation
DNS records for subdomains managed as main domains (i.e. have
ismainbutsubto>1) get written to separate zone files for each subdomain.
This does not play well with hidden-master setups, where a quering DNS
server would only request a transfer of the topmost parent zone and ignore
SOA records therein to initiate the potentially required transfers of
subzones.
This patch changes how zonefiles are created, so that DNS records of
"ismainbutsubto>1"-domains end up within the zone of the topmost parent
domain. Obviously this relies on correctly set ismainbutsubto-fields of
all subdomains managed as main domain in Froxlor.
Refactoring summary:
- Previously _generateDomainConfig() would be called for each customer
domain, handle writing the zone file and …
> cron tasks: bind: refactor zone creation

- lng/german.lng.php
> Fix more typos and other issues in German translation

- lib/configfiles/gentoo.xml
- lib/configfiles/jessie.xml
- lib/configfiles/precise.xml
- lib/configfiles/rhel_centos.xml
- lib/configfiles/trusty.xml
- lib/configfiles/wheezy.xml
Reverts Froxlor/Froxlor#299 as RLimitChroot is nothing froxlor should decide
> Revert "Changes in the config templates"

- admin_autoupdate.php
- lib/classes/ssl/class.lescript.php
- lib/init.php
Most of them were found by codespell.
> Fix some typos in code comments

- scripts/jobs/cron_tasks.inc.http.20.lighttpd.php
- scripts/jobs/cron_tasks.inc.http.30.nginx.php
For Nginx & lighttpd. For Apache the log levels are already set correctly.
> Set correct error log levels (LOG_ERR instead of LOG_ERROR)

- install/scripts/language-check.php
The function "print_help" expects an argument.
> Add missing function argument

- lib/navigation/00.froxlor.main.php
> Revert "Zeige die neue vHost-Konfiguration auch wenn nur mod_php installiert ist." as part of reverting vhost-templates

- admin_domains.php
- admin_vhostsettings.php
- install/froxlor.sql
- lib/formfields/admin/vhostconfig/formfield.vhostconfig_add.php
- lib/formfields/admin/vhostconfig/formfield.vhostconfig_edit.php
- scripts/jobs/cron_tasks.inc.http.10.apache.php
- scripts/jobs/cron_tasks.inc.http.20.lighttpd.php
- scripts/jobs/cron_tasks.inc.http.30.nginx.php
- templates/Sparkle/admin/vhostconfig/overview.tpl
- templates/Sparkle/admin/vhostconfig/overview_overview.tpl
This reverts commit 319668d38460db6a7b5963fd9f66990100852fb9, reversing
changes made to aa592c73699c68fba6c23ef0b03cb6921951f9bf.
> Revert "Merge pull request #326 from Churro/froxlorMerge_vhostTemplates"

- install/lib/class.FroxlorInstall.php
- lib/classes/database/class.Database.php
In case the database is not responding, e.g. due to "too many connections"
cut-off database credentials might be shown and system path be revealed.
In terms of security this is considered as information disclosure.
> [SECURITY] Information disclosure on database failures

- .gitignore
- install/scripts/language-check.php
- install/scripts/switch-server-ip.php
- lib/.gitignore
- templates/.gitignore
they would end up in .deb packages
> don't split .gitignore

- lib/classes/output/class.htmlform.php
(+remove commented out code in the vicinity, probably debugging remnants)
> generic html form handling: don't remove leading tabs

- scripts/jobs/cron_tasks.inc.http.30.nginx.php
Nothing new added, just fixed the indent of some lines
> Fixed formatting

- lib/classes/ssl/class.lescript.php
Change the process to first create a new registration, which delivers the current TOS url in the response's header, then modify the newly created registration to accept the agreement.
> Remove dependency on hard coded agreement URL for Let's Encrypt

- scripts/jobs/cron_tasks.inc.http.30.nginx.php
Use correct variable for hsts in nginx
> Fix sslsettings in hsts for nginx

- install/froxlor.sql
- install/updates/froxlor/0.9/update_0.9.inc.php
Hi,
I manipulate Froxlor tables from my own scripts and think that this constraint will be right in this table.
> Prevent duplicates in ipsandports table

- install/templates/dataitemchk.tpl
<span> must be terminated by </span>.
> Fix HTML code (wrong tag)

- customer_logger.php
Fix customer logs:
- SQLSTATE[HY000]: General error: mode must be an integer
- customer_logger.php:78 Undefined variable $_actions
> Fix customer logs

- lib/classes/ssl/class.lescript.php
as discussed [1] dont send challenge to LE if token for URL could not be fetched
[1] https://github.com/Froxlor/Froxlor/pull/459/files/838b58e24b3d05adc52846743bbdf876b5ddd453#r126209921
> dont send uri to challenge, if no valid token could be fetched

- lib/formfields/admin/domains/formfield.domains_add.php
- lib/formfields/admin/domains/formfield.domains_edit.php
- scripts/jobs/cron_tasks.inc.http.10.apache.php
- scripts/jobs/cron_tasks.inc.http.30.nginx.php
http2 could be set if you add or edit a domain even if http2 is disabled in the settings
> http2 could be set even if http2 is not enabled

- install/lib/class.FroxlorInstall.php
Just noticed this wile automating installation.
> Froxlor installer: Use same file path for chmod.

- lng/english.lng.php
- lng/german.lng.php
Hostname is validated to be a valid domain name.
I just fixed the error message. I don't know if strict validation is that useful - it makes it impossible to install froxlor on localhost / any other local TLD without tricks.
> Fix hostname error message

- lib/configfiles/xenial.xml
Added config template for Ubuntu Xenial 16.04.
> added xenial.xml

- scripts/jobs/cron_tasks.inc.http.30.nginx.php
> Revert "acme challenges can include hyphens (-)"

- install/froxlor.sql
- install/updates/froxlor/0.9/update_0.9.inc.php
- lib/classes/ssl/class.lescript_v2.php
- scripts/jobs/cron_letsencrypt_v2.php
When requesting a certificate for multiple Domains/SANs, the request must be done in a single order.
> Fixed class.lescript_v2.php to work with ACMEv2

- templates/Sparkle/assets/js/circular.js
- templates/Sparkle/assets/js/customers.js
- templates/Sparkle/assets/js/domains.js
See https://lgtm.com/projects/g/Froxlor/Froxlor/alerts/.
> Fix warnings from LGTM

- actions/admin/settings/131.ssl.php
Confirmed working with Apache2
> Add TLSv1.3

- install/templates/assets/css/install.css
- templates/Sparkle/assets/css/dark.css
- templates/Sparkle/assets/css/froxlor.css
- templates/Sparkle/assets/css/main.css
- templates/Sparkle/assets/css/main_ie.css
- templates/misc/awstats/nav.html
- templates/misc/standardcustomer/index.html
- Removes unit if value is 0
- Uses shorthand notation where possible
> Some minor CSS improvements

- install/templates/assets/css/install.css
- install/templates/dataitem.tpl
Correct alignment of radio options
Fixes design-problem with chrome
Before: 
After:
> Improves CSS in installer

- lib/formfields/admin/admin/formfield.admin_add.php
little Bug, requested "new_loginname" instead of "loginname"
> Change formfield id for new admins

- composer.json
If somebody publishs it on packagist, it will allow users to install froxlor via composer. 
I just filled it with the things I considered correct... but maybe I'm wrong...
> Adds first composer.json file

- lng/dutch.lng.php
Corrected spelling errors and typos in the Dutch translations.
> Corrections to the Dutch translations

- lng/english.lng.php
Please include a summary of the change and which issue is fixed if any. Please also include relevant motivation and context. List any dependencies that are required for this change.
* Webserver:
* PHP:
* etc.etc.:
> Corrections to the English texts

- lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php
Only run acme.sh upgrade command once when cronjob starts, and not everytime when there's a certificate going to be renewed.
> Run acme.sh upgrade just once when cron starts

- lib/configfiles/gentoo.xml
- lib/configfiles/jessie.xml
- lib/configfiles/precise.xml
- lib/configfiles/rhel_centos.xml
- lib/configfiles/stretch.xml
- lib/configfiles/trusty.xml
- lib/configfiles/xenial.xml
>  logrotate snipet: (more) GDPR ‚compliant‘

- lib/classes/api/abstract.ApiCommand.php
- lib/classes/api/commands/class.Admins.php
- lib/classes/api/commands/class.Certificates.php
- lib/classes/api/commands/class.Cronjobs.php
- lib/classes/api/commands/class.CustomerBackups.php
- lib/classes/api/commands/class.Customers.php
- lib/classes/api/commands/class.DirOptions.php
- lib/classes/api/commands/class.DirProtections.php
- lib/classes/api/commands/class.DomainZones.php
- lib/classes/api/commands/class.Domains.php
- lib/classes/api/commands/class.EmailAccounts.php
- lib/classes/api/commands/class.EmailForwarders.php
- lib/classes/api/commands/class.Emails.php
- lib/classes/api/commands/class.FpmDaemons.php
- lib/classes/api/commands/class.Froxlor.php
- lib/classes/api/commands/class.Ftps.php
- lib/classes/api/commands/class.IpsAndPorts.php
- lib/classes/api/commands/class.Mysqls.php
- lib/classes/api/commands/class.PhpSettings.php
- lib/classes/api/commands/class.SubDomains.php
- lib/classes/api/commands/class.Traffic.php
> Corrects annotations in API

- lib/init.php
Fehlermeldung wenn Vendor-Ordner Fehlt
> Fehlermeldung wenn Vendor-Ordner Fehlt

- install/install.php
Fehlermeldung wenn Vendor-Ordner fehlt bei der installation
> Fehlermeldung wenn Vendor-Ordner fehlt bei der installation

- lng/english.lng.php
fix obvious typo in `lng/english.lng.php`
> lng/english.lng.php: fix typo

- lib/Froxlor/Api/Commands/Certificates.php
> Add expiration date to SSL certificates loaded via API request

- install/updates/froxlor/0.10/update_0.10.inc.php
> fixing typo

- tests/Froxlor/ValidateTest.php
After #679 is now merged, this adds some unit tests for `Validate::is_ipv6`
> Add UnitTests for #679

- lib/Froxlor/Cron/Http/Nginx.php
Fixed indent for `dhparam` config line
> Fix dhparam indent

- templates/Sparkle/admin/admins/admins_admin.tpl
- templates/Sparkle/admin/customers/customers_customer.tpl
#134 Description
This will show the usage also on accounts that have no limit
Tested on my local installation
* Distribution: debian 9
* Webserver: apache2
* PHP: 7.0
> show disk-usage also on unlimited accounts

- lib/configfiles/rhel7.xml
Adds named dns to RHEL 7 config
Tested it on a clean centos 7 host
* Distribution: CentOS 7
* Webserver: Apache 2.4
* PHP: 7.2
* Bind 9
> Named DNS for RHEL7

- lib/configfiles/centos8.xml
- lib/configfiles/rhel8.xml
Add support for RHEL 8-like systems
* Distribution: CentOS 8.0
* Webserver: Apache 2.4
* PHP: 7.2
> Add CentOS 8 config file

- install/lib/class.FroxlorInstall.php
fixes 2 bugs in distribution detection.
> fix bugs in dist detection

- install/lib/class.FroxlorInstall.php
- lib/Froxlor/Cli/Action/ConfigServicesAction.php
Adds distribution auto detection to CLI interface
> Auto detection in CLI & checks

- install/froxlor.sql
- install/updates/froxlor/0.10/update_0.10.inc.php
- lib/Froxlor/Froxlor.php
issue 868 : Add new performance indexes Fixes # (issue)
> issue 868 : Add new performance indexes

- robots.txt
Search engine and all Robots should be denied to the whole Froxlor directory. This file will help!
-New feature (non-breaking change which adds functionality)
This is a very famous robot file
> Deny all robots

- admin_admins.php
- admin_customers.php
- admin_domains.php
- customer_domains.php
- lib/Froxlor/Api/Commands/Admins.php
- lib/Froxlor/Api/Commands/Customers.php
- lib/Froxlor/PhpHelper.php
- lib/Froxlor/System/IgnorantRecursiveDirectoryIterator.php
Silence some php 8.1 warnings/errors.
> Silence some php 8.1 warnings/errors

- lng/en.lng.php
Please include a summary of the change and which issue is fixed if any. Please also include relevant motivation and context. List any dependencies that are required for this change.
* Webserver:
* PHP:
* etc.etc.:
> Deleted duplicated string

- lng/en.lng.php
- lng/es.lng.php
> Add Spanish language

- lng/en.lng.php
This PR fixes a typo in the English language file.
It hasn't. I'd argue that this is safe to merge without testing :D
> Fix typo in English privileged_passwd

- lib/Froxlor/Cron/Http/Nginx.php
> Correcting Nginx location match, issue #1153

- lib/Froxlor/Api/Commands/DomainZones.php
- lib/formfields/formfield.dns_add.php
- lng/en.lng.php
Adding DNS TLSA support into DNS Editor
Ubuntu 22.04
PHP 8.1.2-1ubuntu2.13
> Added support DNS TLSA record

- templates/Froxlor/src/js/components/search.js
- templates/Froxlor/userarea.html.twig
First TAB goes to the search, second goes to the results, if there are found any.
alternative for #1180
> Add tabindex to search

- lng/ca.lng.php
- lng/en.lng.php
Added ca (catalan) language
I tested it on my own server with:
Debian 11.7, postfix, dovecot, Froxlor 2.0.23-1, MariaDB 10.5.19, Apache2 2.4.56, PHP 7.4
> added ca language

- lib/Froxlor/Install/Install/Core.php
PR reads `ftpserver` from database during install in order to enable customization via .xml distribution file. (similar to existing possibility to customize traffic analyzer)
* Distribution: Debian Bookworm, Gentoo
> Use `ftpserver` from .xml during install

- lib/configfiles/noble
- lib/configfiles/noble.xml
Adding config for Ubuntu 24.04. Changed needed changes, like jammy to noble and 22.04 to 24.04. From my testing i didnt faced any other issues with the config of 22.04
> Add config for Ubuntu 24.04 - Noble Numbat

- lng/cz.lng.php
> Add new missing strings + fix typo

- lng/hu.lng.php
Fixed some missing translations.
* Webserver:
* PHP:
* etc.etc.:
> Update for Hungarian language
