customer_extras.php, install/lib/class.FroxlorInstall.php, install/updates/froxlor/0.9/update_0.9.inc.php, install/updates/preconfig/0.9/preconfig_0.9.inc.php, lib/classes/Smarty-3.1.21/README, lib/classes/Smarty-3.1.21/SMARTY_3.1_NOTES.txt, lib/classes/Smarty-3.1.21/change_log.txt, lib/classes/Smarty-3.1.21/libs/SmartyBC.class.php, lib/classes/Smarty-3.1.21/libs/sysplugins/smarty_internal_template.php, lib/classes/Smarty-3.1.21/libs/sysplugins/smarty_internal_templatebase.php, lib/classes/idna/class.idna_convert.php, lib/classes/idna/class.idna_convert_wrapper.php, lib/classes/integrity/class.IntegrityCheck.php, lib/classes/phpinterface/class.phpinterface_fpm.php, lib/configfiles/wheezy.inc.php, lib/cron_init.php, lib/functions/filedir/function.findDirs.php, lib/functions/filedir/function.makePathfield.php, lib/functions/froxlor/function.moveCustomerToAdmin.php, lib/functions/phphelpers/function.replace_variables.php, lng/english.lng.php, locales/de/LC_MESSAGES/default.po, locales/en/LC_MESSAGES/default.po, scripts/jobs/cron_mailboxsize.php, scripts/jobs/cron_tasks.inc.dns.10.bind.php, scripts/jobs/cron_tasks.php, templates/Sparkle/misc/dberrornice.tpl, templates/misc/configfiles/debian_wheezy/pure-ftpd/etc_pure-ftpd_db_mysql.conf, webftp.php
Most of them are in comments, strings or documentation.
=> Fix typos found by codespell

templates/Sparkle/admin/settings/settings_group.tpl
"discard changes" and "save" on top of each other in security options; there was missing this additional template to fix the bug definitely.
=> Fix Bug #1488

lib/tables.inc.php
Add the define for the mail_autoresponder table. This define is needed in the update_0.9.inc.php script which is used when updating from an early version of froxlor or from SysCP.
=> Add missing table definition for table 'mail_autoresponder'.

scripts/jobs/cron_traffic.inc.functions.php
I might have made a minor typo there. It does not error out when the awstats file is non-existent.
=> Correcting a minor type in Feature #545

lib/classes/webserver/class.ConfigIO.php, lib/functions/filedir/function.makeCorrectDir.php
Steps to reproduce:
1. set Settings->Webserver->Apache->vhost configuration directory to some nonexistent path
2.  run cronjob with `--force` and watch Froxlor trying to delete all files matching `/^([0-9]){2}_(froxlor|syscp)_(.+)\.conf$/`, starting from `/`
Explanation: `ConfigIO::_getFile()` returns `false` for nonexistent files. And `makeCorrectDir(false)` yields `/`. So Froxlor will try to delete every file on all mounted filesystems, which matches the pattern above.
=> fix potentially dangerous programming

scripts/jobs/cron_tasks.inc.http.30.nginx.php
Since the composing of the ssl settings got seperated it still used variables not available in the function scope and broke the regeneration of the ip/ports config files.
=> Fixed composeSslSettings 

lib/configfiles/jessie.xml, lib/configfiles/rhel_centos.xml, lib/configfiles/trusty.xml, lib/configfiles/wheezy.xml
1) Since Dovecot 2.x, quota rules are by default in bytes,
and not in kilobytes (hence multiplicating with 1024 is
not going to be megabytes). Fixed this by adding 'M' suffix.
2) Since Dovecot 2.x, the quota rule is always named `quota_rule`
or (for userdb prefetch) `userdb_quota_rule` (there were some
incorrect namings in the distribution configs).
Ref: http://wiki2.dovecot.org/Quota/Configuration#MySQL
Additional info: This is already correct in the gentoo configuration;
https://github.com/Froxlor/Froxlor/blob/master/lib/configfiles/gentoo.xml#L1557
Maybe we all should put an eye on, that the distribution configs stays a little bit synchron :P
=> Fix problems in Dovecot quota configuration:

scripts/jobs/cron_tasks.inc.http.30.nginx.php
- previously the ssl settings were missing in rewrite vhosts
- this caused ssl errors for these hosts as the default certificate has been used instead of the vhost specific cert.
- this seem to only apply for nginx, not apache
=> fix ssl setttings for rewrite vhosts on nginx, fixes #1568

admin_domains.php
Database::pexecute is based on execute which is a void function.
It does not return a value which can be assigned to a variable.
=> Don't assign variable from void function

lib/classes/phpinterface/class.phpinterface_fpm.php
these are required for custom php configuration for roundcube webmail
=> added php_flag 'suhosin.session.encrypt' and 'mbstring.func_overload'

lib/configfiles/gentoo.xml, lib/configfiles/jessie.xml, lib/configfiles/precise.xml, lib/configfiles/trusty.xml, lib/configfiles/wheezy.xml
remove duplicate fastcgi_index from config templates
=> Duplicate fastcgi_index

lib/functions/filedir/function.makeSecurePath.php
This fix ensures that the result of str_replace() is taken into account for the path that is returned.
=> fix blacklisting of characters in paths

lib/functions/filedir/function.makeSecurePath.php
This fix prevents directory traverals where a blacklisted character is injected in between two dots: `"/.\0./"`
=> prevent directory traversal in paths

scripts/jobs/cron_tasks.inc.dns.10.bind.php
These patches take into account a domain's setting of isemaildomain and wwwserveralias for the creation of A/AAAA-records (www, pop3, imap, smtp) and TXT-records (SPF)
=> cron_tasks/bind: cleanup conditions for creation of mail-related and www DNS records

scripts/jobs/cron_tasks.inc.http.30.nginx.php
Including fastcgi_params twice is causing these errors when generating the config with Froxlor:
[emerg] "fastcgi_connect_timeout" directive is duplicate in /etc/nginx/fastcgi_params:1
I removed the "standard" fastcgi_params but left the parameters in the database, that way an individual could change the parameters on a case-by-case basis without touching the 'native' stuff the packager has put in.
=> Fixes nginx error due to duplicate fastcgi parameters

lib/functions/formfields/text/function.getFormFieldDataText.php
Previously webserver configs would contain CRLFs from
system.default_vhostconf on admin_settings.php.
This patch adds a new function which automatically gets recognized by
getFormFieldData() and mangles textarea form elements through
str_replace("\r\n", "\n", ...).
=> add function getFormFieldDataText()

install/updates/froxlor/0.9/update_0.9.inc.php
A typo in the name of a local variable prevented database updates.
Fix also an unrelated whitespace issue in an empty code line.
=> Fix update process from Froxlor version 0.9.28-svn1

scripts/jobs/cron_letsencrypt.php
The domain should be visible in the warning, not ssl-redirect.
=> Edited warning for letsencrypt to show domain instead of ssl_redirect

lib/classes/phpinterface/class.phpinterface_fpm.php
With Apache 2.4.12, the FPM socket path is always considered as a
lowercase file path regardless of the used capitalization.
If Froxlor creates a socket file containing uppercase characters, Apache fails to find to the socket.
See https://bz.apache.org/bugzilla/show_bug.cgi?id=57968
=> Fix for case insensitivity bug in Apache 2.4.12 + PHP-FPM

scripts/jobs/cron_tasks.inc.http.30.nginx.php, scripts/jobs/cron_tasks.inc.http.35.nginx_phpfpm.php
**Problem:**
The implemented directory protection does not reliably prevent access to PHP scripts.
Having set a username/password for a specific folder, you are shown a prompt when accessing http://...com/protectedir/
Nevertheless, it is still possible to call http://...com/protectedir/script.php
**directly without having to enter credentials**.
This vulnerability emerges from the precedence order of "location" statements. The RegEx matching the PHP script is triggered before the directory protection is evaluated. As a result, the PHP script is
interpreted and path parsing stops due to the circumflex (see http://nginx.org/en/docs/http/ngx_http_core_module.html#location).
**Solution:**
The fix involves adding a separate PHP parsing snippet to every protected block. In order to prevent …
=> Nginx: Security-critical fix for faulty directory protection

install/lib/class.FroxlorInstall.php
**Problem:**
The current _fastcgi_ipcdir_ refers to a directory that is not necessarily existing. Whether the path _/var/run/nginx/_ is created by Nginx depends on the used installation. When using the nginx package from Debian, the path is set-up upon installation. Otherwise, if nginx is compiled from source or fetched as package from the offical repo (nginx.org), the directory is not created.
**Solution:**
Set the path to a directory that is existing regardless of the provenience of the nginx installation.
=> Nginx: Change fastcgi IPC dir to a path that is definitely existing

.gitignore
Stop Git-tracking internal files from Intellij IDEA or WebStorm (cf. Eclipse project files)
=> .gitignore update for Idea or WebStorm files

admin_ipsandports.php, lib/formfields/admin/ipsandports/formfield.ipsandports_add.php, lib/formfields/admin/ipsandports/formfield.ipsandports_edit.php, templates/Sparkle/admin/ipsandports/ipsandports.tpl, templates/Sparkle/admin/ipsandports/ipsandports_ipandport.tpl
**Problem:**
Nginx does not know listen statements, NameVirtualHost and ServerName unknown to lighttpd and nginx.
Nevertheless, these directives are outlined when using webservers that do not support them.
**Solution:**
Only show options that are relevant for the currently active webserver.
_Note:_ In practice, it is conceivable that someone would switch the Webserver from nginx to Apache. However, this should be no problem either since all fields are assigned default values in the db schema.
=> IPs and Ports: Only show attributes used by the current webserver

lng/english.lng.php, lng/german.lng.php, templates/Sparkle/admin/configfiles/configfiles.tpl, templates/Sparkle/assets/js/main.js
**Problem:**
All textarea fields are set read-only and cannot be changed inline. Depending on the service to configure, it might happen that you have to replace the MYSQL_PASSWORD numerous times, e.g. when setting up Postfix with all the mysql-* files.
Having to set this variable over and over is tedious, annoying and prone to typos. Aside from that, you may miss one occurrence to replace and then spend precious time on retracing your mistake.
**Solution:**
Once per template, make the MYSQL_PASSWORD field dynamically configurable. The admin enters the password on the client-side (only), it is propagated over all textareas of the current config template and you can then really simply copy-and-paste the resulting fragments.
=> Feature: Make the MYSQL_PASSWORD string dynamically definable

actions/admin/settings/125.cronjob.php, install/froxlor.sql, lib/configfiles/jessie.xml, lib/configfiles/precise.xml, lib/configfiles/trusty.xml, lib/configfiles/wheezy.xml, lib/functions/froxlor/function.phpErrHandler.php
**Problem 1:**
Obvious the $errcontext parameter can be set null with PHP 7. If strict-typed as _array_, a fatal error occurs.
**Solution 1:**
Remove the type annotation in order to resolve the fatal error.
----- 
**Problem 2:**
Denoting the PHP interpreter at /usr/bin/php5 impedes the use of PHP7, since you must not forget to adapt every occurrence of php5 when upgrading. 
**Solution 2:**
Change the interpreter path to /usr/bin/php. This is not only the default location by design but also ensures flexibility when switching between major versions, e.g. PHP 5 and PHP 7.
=> Fix fatal error in phpErrHandler with PHP7 and suit cronjob for various PHP versions

scripts/jobs/cron_tasks.inc.http.30.nginx.php
**Problem:**
Specifying same index parameter multiple times is considered bad practice (https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#multiple-index-directives).
**Solution:**
Specify the index once in the top-level hierarchy and omit further declarations.
=> Nginx: Avoid multiple index directives (common pitfall)

scripts/jobs/cron_tasks.inc.http.30.nginx.php
Why change the curve for ECDH key exchange from secp256r1 to secp384r1?
Because in the security world, we are practically heading towards RSA 4096-bit keypairs for TLS usage. An elliptic curve with primes of 256 bits relates to the cryptographic strength of a 3072-bits RSA key. Hence, for a sufficiently strong key exchange, we may also choose a curve for ECDH key exchange that is at least 384-bits. For a comparison, this corresponds to the equivalent of a 7680-bits RSA key or a 192-bits of symmetric key.
Basically, all browsers and servers supporting secp256r1 also provide secp384r1. Hence, compatibility issues are almost not existing. The change towards secp384r1 may involve only one downside: the used openssl implementation might not be as optimized as the one for secp256r1.
=> Nginx: Set default curve to secp384r1

scripts/jobs/cron_tasks.inc.http.10.apache.php, scripts/jobs/cron_tasks.inc.http.15.apache_fcgid.php
Problem:
Since Apache 2.3.9 the default setting for AllowOverride has been changed to None [1]. Now without a permissive setting of AllowOverride, this leads to an error, such as:
(13)Permission denied: /var/customers/webs/.../.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable
Manual fixes have been suggested several times [2][3][4][5][6]. However, instead of setting custom Vhost settings for every client who needs .htaccess files, or instead of writing a global diroptions file manually, it seems more reasonable to simply add the option when creating a Vhost. This adds no problems with Apache 2.2 (since it is the standard settings there anyway) and solves the annoying error with Apache 2.4.
[1] https://httpd.apache.org/docs/2.4/mod/core.html#allowoverride
[2] …
=> Apache 2.4: Add AllowOverride All, otherwise Apache ignores .htaccess files

scripts/jobs/cron_tasks.inc.http.30.nginx.php
The problem occurs if a Vhost is assigned multiple different auth names
in Froxlor. Each block is then added repeatedly, leading to an
unparseable configuration
=> Nginx: Fix for redundantly inserted auth blocks

actions/admin/settings/120.system.php, admin_customers.php, admin_ipsandports.php, lib/classes/integrity/class.IntegrityCheck.php, lib/formfields/admin/domains/formfield.domains_add.php, lib/functions/settings/function.storeSettingDefaultIp.php
**Problem:**
Until now, it was only possible to specify one IP address used for new domains by default. This is annoying if you run a dual-stack setup with IPv4 and IPv6 (cf. https://redmine.froxlor.org/issues/1509). 
**Solution:**
Make more than one IP address eligible by default. The solution has been tested working on many different hosts and is also suited to be applied as an update on-top of the existing setting.
=> Feature: Enable multiple standard IPs

lib/classes/ssl/class.lescript.php, lib/configfiles/trusty.xml, scripts/jobs/cron_tasks.inc.http.30.nginx.php
class.lescript.php: OpenSSL requires integer for key size. DB returns string. Cast string to integer
trusty.xml: All files in conf.d get automatically included causing the location to be out of place and nginx fails to start. Also, the alias works slightly different in nginx than it does in Apache.
cron_tasks.inc.http.30.nginx.php: Location directives should be included in a host, nginx doesn't have the concept of global location directives in the way apache does. When PHP variables aren't defined, it throws a warning polluting the cronjob logs and sending e-mails.
=> Various fixes for failing nginx/LetsEncrypt

admin_autoupdate.php, lng/english.lng.php
**Problem:**
Currently, the autoupdater suffers from two vulnerabilities:
1. The Froxlor host can be tricked into updating with a non-official (or even backdoored) update archive. Using DNS spoofing an attacker is able to perform Cache Poisoning on the host running Froxlor. For an attacker, it is then easy to masquerade as autoupdate.froxlor.org since the connection is HTTP only.
2. It is trivial to produce an update archive which has the same MD5 hashsum as the official one. MD5 is known to be officially broken for more than 10 years now, it takes modern GPUs only < 30min to find a collision. Any modification to the update file would hence not be detectable. However, since the checksum is delivered using HTTP anyway, an attacker may deliver any hashsum.
**Solution**:
- Change HTTP to …
=> Improve autoupdate against HTTP MITM and MD5 collisions

admin_domains.php, admin_phpsettings.php, admin_vhostsettings.php, install/froxlor.sql, install/updates/froxlor/0.9/update_0.9.inc.php, lib/formfields/admin/domains/formfield.domains_add.php, lib/formfields/admin/domains/formfield.domains_edit.php, lib/formfields/admin/vhostconfig/formfield.vhostconfig_add.php, lib/formfields/admin/vhostconfig/formfield.vhostconfig_edit.php, lib/navigation/00.froxlor.main.php, lib/tables.inc.php, lib/version.inc.php, lng/english.lng.php, lng/german.lng.php, scripts/jobs/cron_tasks.inc.http.10.apache.php, scripts/jobs/cron_tasks.inc.http.20.lighttpd.php, scripts/jobs/cron_tasks.inc.http.30.nginx.php, scripts/jobs/cron_tasks.inc.http.35.nginx_phpfpm.php, templates/Sparkle/admin/vhostconfig/overview.tpl, templates/Sparkle/admin/vhostconfig/overview_add.tpl, templates/Sparkle/admin/vhostconfig/overview_edit.tpl, templates/Sparkle/admin/vhostconfig/overview_overview.tpl
@hpmewes presented a nice implementation of pre-definable vHost templates in PR #233 .
Presumably due to some unresolved issues, his implementation has not been merged finally and remained as a pending pull request.
In this PR, a reworked implementation is provided with:
- bugfixes all over
- added support for apache and lighttpd also
- added an update sequence (instead of only modifying froxlor.sql)
- added english language variables
- added missing parts in admin_vhostsettings.php
- added parameter replacements as available since PR #244 
The solution has been tested working on different setups and should integrate / upgrade flawlessly.
=> Feature: vHost templates (version 2)

admin_domains.php, admin_vhostsettings.php, install/froxlor.sql, install/updates/froxlor/0.9/update_0.9.inc.php, lib/formfields/admin/vhostconfig/formfield.vhostconfig_add.php, lib/formfields/admin/vhostconfig/formfield.vhostconfig_edit.php, lib/version.inc.php, scripts/jobs/cron_tasks.inc.http.10.apache.php, scripts/jobs/cron_tasks.inc.http.20.lighttpd.php, scripts/jobs/cron_tasks.inc.http.30.nginx.php, templates/Sparkle/admin/vhostconfig/overview.tpl, templates/Sparkle/admin/vhostconfig/overview_overview.tpl
This PR enables Vhost templates to be assigned a specific webserver. 
This is not only useful if you consider switching from one server system to another, e.g. nginx -> Apache. It also prevents that a template is loaded for a webserver it is not suited for.
Other improvements in this PR:
- Cleaned admin_vhostsettings.php from useless overhead and tried to make it easier readable.
- Refential integrity is now provided: The cron scripts check whether the referenced template is actually existing before proceeding. Likewise, if a template is deleted, the reference is reset for the domains using it.
=> Vhost templates: Added a field to select the target webserver

lib/configfiles/gentoo.xml, lib/configfiles/jessie.xml, lib/configfiles/precise.xml, lib/configfiles/trusty.xml, lib/configfiles/wheezy.xml
From a security perspective, it seems adequate to enable TLS for FTP by default. This also fixes bug report #1522 which postulates settings that also comply with FileZilla.
=> ProFTPD: enable TLS by default. Fixes #1522

lib/navigation/00.froxlor.main.php
Ich behaupte mal das weder fpm noch fcgid nötig sind dafür. Vermutlich einfach copy&paste gewesen? :P
=> Zeige die neue vHost-Konfiguration auch wenn nur mod_php installiert ist.

lib/configfiles/gentoo.xml, lib/configfiles/jessie.xml, lib/configfiles/precise.xml, lib/configfiles/rhel_centos.xml, lib/configfiles/trusty.xml, lib/configfiles/wheezy.xml
If you configure Froxlor properly to a valid FQDN like srv.domain.tld you would want to set myhostname in postfix to that FQDN and not as previously to mail.srv.domain.tld
=> Set myhostname to $mydomain in postfix

scripts/jobs/cron_letsencrypt.php
The column ssl_cert_chainfile in the domain_ssl_settings tablet should only contain the intermediate certificate. Using the fullcert from let's encrypt leads on using nginx to a certificate file like this:
[Certificate]
[Certificate]
[Intermediate Certificate]
Not a real problem but the check on ssllabs.com shows a error message:
[https://community.qualys.com/docs/DOC-1931](url)
=> ssl_cert_chainfile should only contain the intermediate certificate

scripts/jobs/cron_tasks.inc.dns.10.bind.php
Hi,
the secondary DNS servers might have multiple IP addresses and the transfer requests might be issued from any of the IP addresses; therefore all IP addresses of the secodnary DNS servers should be allowed to transfer zones. I had this fix added to my old syscp installation for some years. 
As I plan to upgrade to a recent Froxlor version I decided to share some of my modifications with you.
Regards
Kay Zumbusch
=> Support for multi homed DNS servers

lib/classes/config/class.ConfigDaemon.php, lib/configfiles/jessie.xml
=> jessie configs: override starting order of apache2 and nscd

lib/classes/ssl/class.lescript.php
The generated account-key is already set to NOT be saved when not using the production environment of LE (since keys are not saved on staging at LE and should be regenerated on every request), but new account-key generation is not triggered when not in production.
So if you have a account-key generated in production (which seems to be the default) and switch to staging afterwards, it'll try to use the production-key, which will fail.
Solution: Simple addition to the if-check.
=> Let's Encrypt: Always regenerate a new account-key, if staging

scripts/froxlor_master_cronjob.php
The old code used the complete filepath for lookups,
then lastrun_update was used to resolve filepath of cron back to it's cron name.
The new code uses the cron name (commandline argument and in the database).
Maybe addToQueue could be extended to return a boolean in the future,
then create a proper error message if the command line argument is wrong.
=> Simplify master cronjob

install/froxlor.sql
Missing comma after dnsenabled
=> BUGFIX: Cleaninstall fails due syntax error in froxlor.sql 

index.php
This commit fixes non-persistent Cross-site scripting (XSS) vulnerability due improper content escaping. Variable `qrystr` is used in template in html attribute content, but it's escaped in generic content (strip_tags).
Vulnerability was found during penetration testing.
=> fix non-persistent XSS due inproper content escaping

dist/deb/wheezy/debian/lintian-overrides
Back in Wheezy some override messages did not yet have package information
associated with them. This adjusts the override taken from Jessie
packaging.
=> Debian/Wheezy packaging: fix lintian-overrides

lib/classes/ssl/class.lescript.php
... while doing the self check.
A rule (e.g. Wordpress plugin iThemes) might block requests with empty
User Agents.
=> Set a User Agent in the HTTP request fetching the LE challenge URI

lib/classes/ssl/class.lescript.php
We have to finish the challenge request so that the auth does not linger in state "pending", but goes to "invalid". See https://forum.froxlor.org/index.php/topic/13463-lets-encrypt-zertifikate-werden-nicht-erneuert/#entry32895
=> do not die after token self check

lib/classes/ssl/class.lescript.php
if no Terms of Service are presented by the ACME server when registering, don't update registration
=> Letsencrypt: only update registration when necessary

scripts/jobs/cron_tasks.inc.http.10.apache.php, scripts/jobs/cron_tasks.inc.http.20.lighttpd.php, scripts/jobs/cron_tasks.inc.http.30.nginx.php
PHP Notice:  Undefined index: parentdomainid in
[…]/froxlor/lib/classes/webserver/class.DomainSSL.php on line 49
=> fix "undefined index" warnings

admin_index.php, lng/english.lng.php, lng/german.lng.php, templates/Sparkle/admin/index/index.tpl
hostname may be useful in situations where several froxlors are
reverse-proxied on a single webserver
=> display system hostname and some memory info on dashboard

admin_domains.php, customer_domains.php, customer_traffic.php, install/froxlor.sql, install/updates/froxlor/0.9/update_0.9.inc.php, lib/version.inc.php
In mysql 5.7 only_full_group_by is enabled by default.
=> fix group by clause to be be compliant with mysql 5.7

actions/admin/settings/130.webserver.php, install/froxlor.sql, install/updates/froxlor/0.9/update_0.9.inc.php, lng/english.lng.php, scripts/jobs/cron_tasks.inc.http.30.nginx.php
I tested this modification and works great. 
I added the setting manually to my panel_settings table. I know nothing how to make the database update in update_0.9.inc.php file, so it commented out the code what I believe to correct.
=> Add support for http2 option to nginx

scripts/jobs/cron_tasks.inc.http.10.apache.php, scripts/jobs/cron_tasks.inc.http.20.lighttpd.php, scripts/jobs/cron_tasks.inc.http.30.nginx.php
When you have enabled "SSL redirect" and have alias domain(s) always redirected to the main https domain: http://maindomain.com -> https://maindomain.com and http://aliasdomain.com -> https://maindomain.com
I think the required operation is to redirect to the requested domain: http://maindomain.com -> https://maindomain.com and http://aliasdomain.com -> https://aliasdomain.com
I tested with nginx, I edited an apache config file with the generated text, but I don't have lighthttpd.
=> Change redirect host from main domain name to requested domain name

README.md
The entry is called "System", not "Server".
=> Fix description in README.md

lib/functions/dns/function.createDomainZone.php
See: https://www.denic.de/fileadmin/public/documentation/DENIC-23p.pdf
The recommended values according to DENIC are:
refresh: 3600 - 86400
retry: 900 - 28800
expire: 604800 - 3600000
negTTL: 180 - 86400
=> Changed SOA refresh intervall to be within recommended values

scripts/jobs/cron_tasks.inc.http.10.apache.php
Disable `SSLCompression` to mitigate CRIME attack.
Source:
https://raymii.org/s/tutorials/Strong_SSL_Security_On_Apache2.html#SSL_Compression_(CRIME_attack)
=> Disable SSLCompression (CRIME attack)

README.md
Correct the links of the no longer existing redmine to Github´s inbuild Wiki
=> Correct Wiki links

lib/classes/integrity/class.IntegrityCheck.php
"ALTER TABLE ... CONVERT TO CHARACTER SET" fails on VIEWs with error like
ERROR 1347 (HY000): 'froxlor.view_xxx' is not BASE TABLE
Views can be created for third-party extensions and API to Froxlor database (see for example opendkim support).
=> Skip views when altering table charsets

admin_customers.php
adddate is a integer column it throws any time a mysql warning.
A database error occurred SQLSTATE[01000]: Warning: 1265 Data truncated for column 'add_date' at row 1
=> Fixed MySQL Warning while creating a new user

actions/admin/settings/131.ssl.php
Add default value for apache24_ocsp_cache_path, otherwise saving
SSL settings for !apache24 fails on apache24_ocsp_cache_path validation.
=> Fix apache24_ocsp_cache_path definition

scripts/jobs/cron_tasks.inc.http.30.nginx.php
`index` directives are now created for secured directory locations, closes #449
=> nginx: add index directive to path options for secured directories

scripts/froxlor_master_cronjob.php, scripts/jobs/cron_tasks.php
If you use libnss-extrausers and create a new customer apache complains about a bad user and fails to restart. You have to clear the users from nscd.
=> Added nscd -i passwd to clear user

templates/Sparkle/ssl_certificates/certs_cert.tpl
As an admin I want to check if the certificate of a website is working.
Therefore I click on the domain in the SSL certificate list and have to prepend "https" to the URL later.
In this case I'd link the domain to HTTPS initially.
=> Link domains to HTTPS in certificate list

admin_domains.php, customer_domains.php
Prior to this, LE CSRs were triggered only when the wwwserveralias was
changed on alias domains, but not on main domains.
Fixes #526
=> fix triggering an LE CSR when changing www on a main domain

scripts/jobs/cron_tasks.inc.http.30.nginx.php
made a small adjustment so that acme challenges like "CrgFuFZU-U7mwXxjjHZi8if851XGVjdPRtWN91LTWmM" also don't get redirected
=> acme challenges can include hyphens (-)

scripts/jobs/cron_tasks.inc.http.30.nginx.php
I extend the regex rule for .well-known location to redirect to https site, because this one was not enough:
if ($request_uri !~ ^/.well-known/acme-challenge/\w+$)
Some Keys from LetsEncrypt cold not redirected because there are "-" signs in Key
Key Example: WgV7aLbGyXrdnFHCIIssDE_914eI9EYwRAoFc5Ci3-w
New check is this:
if ($request_uri !~ ^/.well-known/acme-challenge/**[\w-]**+$) {
=> extend nginx letsencrypt (.well-known) redirect regex to https

install/lib/class.FroxlorInstall.php
Otherwise it is not possible to install current master due to fatal error
` PHP Fatal error:  Uncaught Error: Non-static method PDO::getAttribute() cannot be called statically in /var/www/html/froxlor/install/lib/class.FroxlorInstall.php:534`
=> Checks Mysql version only if no fatal error occured

lib/Froxlor/Cron/Http/Nginx.php
Only apply htpasswd rules to (sub)domains if the rule's path begins with the domain's document root.
=> htpasswd only on configured paths

lib/Froxlor/Validate/Form/Data.php
As described in #675 this patch fixes the non existing function with the static method call.
Installed 0.10.0-rc1 locally to see how it performed. Tried changing values in the admin menu (panel) and encountered the bug explained in #675 .
=> fixes #675

lib/Froxlor/MailLogParser.php
The mail log parsing regex was incorrectly using a character group of `\A`
Fixes #682
* Distribution: debian
* Webserver: N/A
* PHP: 7.3.5-1+0\~20190503093914.38+buster\~1.gbp60a41b
=> Fixes #682 - mail log parsing regex character group

lib/configfiles/bionic.xml, lib/configfiles/buster.xml, lib/configfiles/gentoo.xml, lib/configfiles/jessie.xml, lib/configfiles/rhel_centos.xml, lib/configfiles/stretch.xml, lib/configfiles/trusty.xml, lib/configfiles/xenial.xml
DIsable mail redirections if customer is disabled.
Fixes #704 
- Add customer with domain
- Add mail redirection
- Send mail -> will be delivered
- Disable customer
- Send mail -> will not be delivered:
> 550 5.1.1 <xxx@example.com>: Recipient address rejected: User unknown in virtual mailbox table
* Distribution: Debian Stretch
* Webserver: nginx
* Mailserver: Postifx
=> Disable mail redirections if customer is disabled

lib/Froxlor/Cron/Http/Nginx.php
Use $request_filename instead of $document_root$fastcgi_script_name as described in: https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#use-request-filename-for-script-filename
=> Updating fastcgi_param

lib/Froxlor/Cron/Http/NginxFcgi.php
Use $request_filename instead of $document_root$fastcgi_script_name as described in: https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#use-request-filename-for-script-filename
=> Updating another fastcgi_param SCRIPT_FILENAME

lib/Froxlor/Cron/Http/Nginx.php
Remove slash after hostname since requests directly to the hostname do not require a slash at the end and all other content goes to `$request_uri` which starts with shlash, hence no longer doubleslashes on hostname only queries.
=> Remove unnecessary slash for SSL redirect

lib/Froxlor/Cron/Dns/PowerDNS.php
Some getDB calls were missing the `\Froxlor\Dns\` prefix
Cron threw an error during initial run:
`PHP Fatal error:  Uncaught Error: Call to undefined method Froxlor\Cron\Dns\PowerDNS::getDB() in /var/www/froxlor/lib/Froxlor/Cron/Dns/PowerDNS.php:115
Stack trace:
#0 /var/www/froxlor/lib/Froxlor/Cron/Dns/PowerDNS.php(72): Froxlor\Cron\Dns\PowerDNS->insertZone('test.froxlor.on...', 2019092201)
#1 /var/www/froxlor/lib/Froxlor/Cron/Dns/PowerDNS.php(41): Froxlor\Cron\Dns\PowerDNS->walkDomainList(Array, Array)
#2 /var/www/froxlor/lib/Froxlor/Cron/System/TasksCron.php(257): Froxlor\Cron\Dns\PowerDNS->writeConfigs()
#3 /var/www/froxlor/lib/Froxlor/Cron/System/TasksCron.php(62): Froxlor\Cron\System\TasksCron::rebuildDnsConfigs()
#4 /var/www/froxlor/lib/Froxlor/Cron/MasterCron.php(101): …
=> fix missing namespaces in PowerDNS cron

lib/Froxlor/Cron/System/MailboxsizeCron.php
When quota is enabled, dovecot generates a [maildirsize file](https://wiki2.dovecot.org/Quota/Maildir#Maildirsize_file). This file can be used to get the current Maildir size. This is quicker & easier than using du. When quota is not enabled, the file is missing & du is used as usual.
Especially when quota integration in Dovecot is actively used, du sometimes reports too big values, leading to confusion why it's different from the value shown in mail clients. The big values come from various files that usually do not count towards maildir size, like index files.
Tested on local configuration with various use-cases (file there, file not there, new user mailbox etc.)
* Distribution: Debian Buster
* Webserver: Apache/2.4.38 …
=> Get mailbox size with maildirsize file

lib/Froxlor/System/MysqlHandler.php
I noticed the System Log in the panel would only show "unkown" as the user. Upon digging into the code, I noticed that the context field is called `user`, not `loginname`. See https://github.com/Froxlor/Froxlor/blob/master/lib/Froxlor/FroxlorLogger.php#L162
Log page now shows users.
Distribution: Debian Buster
Webserver: Apache/2.4.38
PHP: PHP 7.3.9-1~deb10u1
=> fix MysqlHandler user field

lib/Froxlor/Cron/Http/Nginx.php, lib/Froxlor/Cron/Http/NginxFcgi.php
With Nginx+PHP fpm the fastcgi_split_path_info parameter is generated wrong:
`                fastcgi_split_path_info ^(.+\.php)(/.+)\$;`
instead of:
`                fastcgi_split_path_info ^(.+\.php)(/.+)$;`
(i.e.: https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/ )
=> Fix fastcgi_split_path_info

templates/Sparkle/2fa/entercode.tpl
added autofocus for 2fa_code
Yes, Chrome, Edge, Firefox, Opera all accepted the tag.
=> enabled autofocus for 2fa_code

lib/Froxlor/Api/Commands/Certificates.php
An SQL error occurs when using the SSL certificate search field.
=> SQL error in lib/Froxlor/Api/Commands/Certificates.php

lib/Froxlor/Cron/Http/Nginx.php
`logtype` can be defined in the settings and should be used consistently across all `access_log` options.
=> Use logtype for access_log for IPsAndPorts too

install/froxlor.sql, install/updates/froxlor/0.10/update_0.10.inc.php, lib/Froxlor/Api/Commands/FpmDaemons.php, lib/Froxlor/Cron/Http/Php/Fpm.php, lib/Froxlor/Froxlor.php, lib/formfields/admin/phpconfig/formfield.fpmconfig_add.php, lib/formfields/admin/phpconfig/formfield.fpmconfig_edit.php, lng/english.lng.php, lng/german.lng.php, templates/Sparkle/admin/phpconfig/fpmconfig_add.tpl, templates/Sparkle/admin/phpconfig/fpmconfig_edit.tpl
Adds the ability to append custom configuration to PHPFPM pool configuration:
Addresses #643
=> Ability to add custom config to PHPFPM version

lib/Froxlor/MailLogParser.php
Fixed parsing due to changes in dovecots default mail_log_prefix since version 2.3
Regex supports old and new default format now
See https://wiki2.dovecot.org/Upgrading/2.3 for changes in mail_log_prefix default settings
Dovecot traffic was not counted anymore, since dovecot changed the default log prefix
- [ x] Bug fix (non-breaking change which fixes an issue)
=> fixed parsing due to changes in dovecots default mail_log_prefix

lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php
The ACME v2 implementation uses separate directoies for ECC and on-ECC
certificates. The renew command for a domain checks if an ECC directory
exists (having a "_ecc" suffix) and refuses the command unless the
"--ecc" flag was specified.
Confusingly, this flag is only required to *renew* an ECC certificate,
but not to issue it.
Fixes https://github.com/Froxlor/Froxlor/issues/820.
* Distribution: Debian GNU/Linux 10 (buster)
* Web server: apache2
* ACME: 2.8.6
=> Fix renewal of ECC/ECDSA certificates.

lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php
Certificate file cannot be read to database if the domain contains capital letters.
=> Certificate file cannot be read to database

lib/formfields/admin/domains/formfield.domains_add.php
TLSv1 is deprecated, I believe it should not be enabled for new domains by default. Will be great to enable TLSv1.3 by default but it might be not available on the older distributions.
=> TLSv1 is deprecated

install/updates/preconfig/0.9/preconfig_0.9.inc.php
During update there is a default suggestion of php5, which is not needed, usually `/etc/alternatives/php` points to the right installed php version.
untested
=> Don't suggest php5 during update as default

lib/configfiles/centos8.xml
This updates the centos8 config with the following changes:
- use DNF instead of YUM (yum is symlinked to dnf in centos8)
- use 'dnf -y install' instead of 'dnf install' to eliminate unnecessary user interaction
- proftpd requires epel repository to be enabled first
- missing create directory for http passwd files
- awstats needs to be installed and requires CentOS PowerTools repository
- awstats cron file is placed in a different directory
=> Centos8 config updated

lib/configfiles/centos7.xml
proftpd requires epel repository to be enabled first
missing create directory for http passwd files
awstats cron file is placed in a different directory
=> proftp requires epel, awstats needs install and awstats cron moved

lib/Froxlor/Cron/Traffic/ReportsCron.php
Proper check for success of query before accessing the result array. 
The following notices occure if there's no custom mail-template for e.g. trafficmaxpercent_subject available for the required language:
```
PHP Notice:  Trying to access array offset on value of type bool in /var/www/froxlor/lib/Froxlor/Cron/Traffic/ReportsCron.php on line 427
PHP Notice:  Trying to access array offset on value of type bool in /var/www/froxlor/lib/Froxlor/Cron/Traffic/ReportsCron.php on line 431
```
I succesfully tested the proposed changes on my own live Froxlor instance in the "Reaching your diskspace limit" use-case.
=> Fix for notices "Trying to access array offset on value of type bool" in ReportsCron.php

install/froxlor.sql
Data integrity - under no circumstances the empty string is a valid value for these columns.
Probably not worth it to remove these default values from existing DBs.
=> Data integrity - remove default values from some columns

lib/Froxlor/Cron/Http/DomainSSL.php
Until now all files in Froxlor's SSL directory are only readable by root. While this is required for the .key files which contain the private keys it isn't necessary for the certificates (and chains) which only contain public keys.
Having the certificates world readable allows external programs executed by non-privileged users to scan the certificates. So it would be possible for a monitoring system to check whether there are expired certificates.
As the certificates are presented to all website visitors there is no reason to protect them.
This change executes chmod 600 only for ssl_key_files and leaves all other files mode 644 (or whatever is requested by umask on global level).
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. …
=> Protect only private keys and leave certificates world readable.

lib/Froxlor/System/Crypt.php
Quoting the default regex delimiter is required for the password
complexity check to work if '/' had been specified as special character
in Froxlor's account settings.
=> system: validatePassword(): also quote the delimiter ('/')

lib/Froxlor/Dns/Dns.php
Quoting the default regex delimiter is required for the password
complexity check to work if '/' had been specified as special character
in Froxlor's account settings.
=> dns: check NS entry to be used as primary NS

actions/admin/settings/160.nameserver.php, install/froxlor.sql, install/updates/froxlor/0.10/update_0.10.inc.php, lib/Froxlor/Dns/Dns.php, lib/Froxlor/Froxlor.php, lng/english.lng.php, lng/german.lng.php
Quoting the default regex delimiter is required for the password
complexity check to work if '/' had been specified as special character
in Froxlor's account settings.
=> dns: make mail address of SOA records configurable

install/lib/class.FroxlorInstall.php
During my tests I found some small bugs in the installer routine, that caused quite some warnings especially with PHP 8, detailed list below:
- Language Select: This has been broken probably for a while now. Simple bug though: Key and Value had been mixed up - switched!
- $groupname: This is not used in the method and there is no $groupname defined to begin with - removed
- Various other initialisations: Concatenate or trying to select array keys or variables that do not exist yet - fixed!
Tested the changes twice in my environment, both from a fresh database. No more warnings, language select works now, install runs successfully.
=> Installer Cleanup & Bug Fixes

lib/Froxlor/Dns/Dns.php
Currently in $soa_content the "Minimun SOA record" is obtained from the system configuration -> TTL and thus may be incorrect. (TTL and Minimum SOA-Records are not the same?! looks like a bug)
In addition, I also fixed the "Expired" entry, according to current [RFC](https://www.ietf.org/rfc/rfc1912.txt) this must be 2 or 4 weeks.
Thanks for merging.
=> Fix Minimum and Expired SOA-Records

actions/admin/settings/131.ssl.php, lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php
Just added Buypass to the list of ACME providers. They provide certificates with a validity of 180 days via ACME. The API URL is documented [here](https://community.buypass.com/t/63d4ay/buypass-go-ssl-endpoints-updated-14-05-2020).
=> Add Buypass to the list of ACME providers.

lib/Froxlor/Cron/Http/ApacheFcgi.php
Added `<If "-f %{SCRIPT_FILENAME}">` to load only PHP files that exists. This is to prevent `File not found` error from PHP-FPM and let Apache handle the error output. It removes also unnecessary PHP-FPM calls and `AH01071: Got error ‘Primary script unknown` in PHP error log.
Usually you can find the error whenever someone goes fishing for paths like wp-login.php.
The `<If>` directive is only available in Apache 2.4+ and not 2.2 or earlier.
* Distribution: Debian 11
* Webserver: Apache 2.4
* PHP-FPM: 7.4, 8.0, 8.1
* Apache module mpm_event used
=> Call PHP-FPM only when file exists

composer.json, composer.lock
This change improves the syntax in composer.json.
1. `php` was listed twice (in `require` and `require-dev`).
2. `>=` syntax should be avoided to account for breaking changes in major PHP versions. `^` allows minor updates, but not major
(3. I would like to see the minimum version raised to PHP 7.4, as 7.1 and 7.2 are no longer updated and should not be supported in my opinion. **Can I also implement this in this PR?**)
--
--
=> Improve composer.json syntax

install/scripts/config-services.php, install/scripts/switch-server-ip.php
If the script is executed unattended a proper return code is useful to abort if there was an error.
=> Set RC 1 if an exception occured

install/lib/class.FroxlorInstall.php, install/lng/english.lng.php, install/lng/french.lng.php, install/lng/german.lng.php, lib/Froxlor/Cron/Http/LighttpdFcgi.php, lib/Froxlor/Cron/Http/NginxFcgi.php, lib/Froxlor/Froxlor.php
remove nested dirname and use level parameter for better readability
```dirname(dirname(dirname(__FILE__)))```
can be replaced with
```dirname(__FILE__, 3)```
=> remove nested dirname and use level parameter for better readability

templates/Sparkle/assets/css/main.css
Currently, if you upload a custom login header image (logo) there is no size limitation, so if its wider than the login box it'll just break the layout. This PR introduces a max-width of 100% (minus the 20px x-axis padding of the parent) for this image to not break the layout.
[x] Bug fix (non-breaking change which fixes an issue)
Yup! :-)
=> Add login header image max-width

templates/Froxlor/form/formfields.html.twig
Fixing incorrect path for preview image in formfield, if you do not run Froxlor in root-directory.
=> Fix formfield image preview path

lib/tablelisting/admin/tablelisting.fpmconfigs.php
Very small UI fix that corrects a table header label
Made change. Reloaded UI. Check if heading now correct.
* Distribution: Ubuntu jammy
* Webserver: nginx
* PHP: 7.4 fpm
=> fixed duplicated column heading in /admin_phpsettings.php?page=fpmdaemons

lib/configfiles/bionic.xml, lib/configfiles/bookworm.xml, lib/configfiles/bullseye.xml, lib/configfiles/buster.xml, lib/configfiles/focal.xml, lib/configfiles/jammy.xml
This extends the configfiles for debian based distros with an additional command to remove a prerotate script included in their pacakges.
The removed script is obsolete with Froxlor because it has it's own cron task for traffic.
Not tested :-P
* Distribution: debian bullseye
* Webserver: apache2
* PHP: 8.2
* etc.etc.: etc.
=> [configfiles] Add command to remove debians prerotate script

templates/Froxlor/login/enter2fa.html.twig
2FA codes change every login. So there is no need to save entered values in browser and suggest them again during future logins.
According to https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete there also exists the value `one-time-code` for `autocomplete`, but e.g. Chrome doesn't support it. That's why the value `off` was chosen.
Tested with browsers:
=> Disable autocomplete on 2FA input element

lib/Froxlor/UI/Panel/UI.php, lib/init.php
This PR fixes the incorrect handling of literal IPv6 addresses in the cookie domain.
Currently, the cookie domain is broken, when using a literal IPv6 address to access Froxlor:
```
➜  ~ curl -sI "http://froxlor.home/froxlor/install/install.php" | grep Set-Cookie
Set-Cookie: PHPSESSID=gd76r4bln50mqim4i310304ckn; expires=Tue, 09-May-2023 23:51:16 GMT; Max-Age=7200; path=/; domain=froxlor.home; HttpOnly; SameSite=Strict
➜  ~ curl -sI "http://froxlor.home:8080/froxlor/install/install.php" | grep Set-Cookie
Set-Cookie: PHPSESSID=nvtgr79p4d1b0ibu75e4l36ktp; expires=Tue, 09-May-2023 23:51:24 GMT; Max-Age=7200; path=/; domain=froxlor.home; HttpOnly; SameSite=Strict
➜  ~ curl -sI "http://192.168.4.4/froxlor/install/install.php" | grep Set-Cookie
Set-Cookie: PHPSESSID=2j0dn1c97cod7i5v62vaej0rma; …
```
=> Fix IPv6 address in cookie domain

bin/froxlor-cli, lib/Froxlor/Cli/ConfigDiff.php
Adds a simple `config-diff` CLI command. A nice-to-have command without the possibility of breaking anything :-)
It accepts two arguments from a list of the available config-templates and compares all files to changes between OS versions.
This enables a quick glance of required config changes when updating the server OS, in case you have customized some configs on your system and have to update config files manually and cannot run the install command again.
Example output comparing `focal` and `jammy`:
=> Add config-diff CLI Command

lib/navigation/00.froxlor.main.php
Seems to have changed when adding the domain-filter overview for email addresses, but not updated in the navigation.
=> Fix "Add" shortcut link in email address navigation

lib/Froxlor/Idna/IdnaWrapper.php
utf8_encode is deprecated since PHP 8.2.0
See [PHP documentation](https://www.php.net/manual/en/function.utf8-encode.php).
- [ X] Bug fix (non-breaking change which fixes an issue)
* Webserver:
* PHP:
* etc.etc.:
- [ X] I have performed a self-review of my own code
=> replace deprecated function utf8_encode

lib/Froxlor/Cli/InstallCommand.php
Make the manual_config var, which is available to the web installer, usuable for the cli installer too. If manual_config is set to true skip else (not set or false) proceed with auto config.
Maybe example in docs needs to be updated, too.
=> Add manual_config install var to cli

lib/Froxlor/Config/ConfigDaemon.php, lib/configfiles/gentoo.xml
ConfigDaemon always uses the first matched element from specified XPath https://github.com/Froxlor/Froxlor/blob/87409473231f7f928ae36bff02362a7e034b9e4f/lib/Froxlor/Config/ConfigDaemon.php#L94 but didn't check if specified XPath matched exactly one element.
The Gentoo config XML has two different versions for the daemon `postfix_dovecot` specified:
- https://github.com/Froxlor/Froxlor/blob/87409473231f7f928ae36bff02362a7e034b9e4f/lib/configfiles/gentoo.xml#L1557
- https://github.com/Froxlor/Froxlor/blob/87409473231f7f928ae36bff02362a7e034b9e4f/lib/configfiles/gentoo.xml#L1705
The second version in line 1705 is missing the `version` attribute. This causes the XPath (based only on the `name` attribute) to match both elements and results in a broken output for service configuration (version …
=> Ensure XPath for ConfigDaemon matches exactly one element

lib/Froxlor/Api/Commands/EmailAccounts.php, tests/Emails/EmailsTest.php
Adding a new mail account on a system without PHP Argon2X support an exception will be triggered.
-> Check if Argon2X is supported in PHP (==constant is defined) before using it.
Adding a mail account on a system without PHP Argon2X support was possible after patch
=> Check for Argon2 support before using constant PASSWORD_ARGON2X

lib/Froxlor/Dns/Dns.php, tests/DomainZones/DomainZonesTest.php
Ensure that DMARC records are always generated as subdomain (see https://datatracker.ietf.org/doc/html/rfc7489#section-6.1).
Additionally ensure that manually specified SPF and DMARC records for subdomains can overwrite default records generated by Froxlor.
- https://dmarcian.com/dmarc-inspector/
- https://www.dmarc-record.de/analyser/
- New unit test
* Distribution: Gentoo
* Nameserver: BIND
=> Ensure that DMARC entries are generated as subdomain, Allow overwriting of DMARC and SPF subdomain records

actions/admin/settings/110.accounts.php, lib/init.php
This fixes the exception: '"expires" option cannot have a year greater than 9999', which happens on upgrade from Debian 11 to 12. The session timeout in the DB is 9999999999999, so we constrain the value.
=> Fix "expires" option cannot have a year greater than 9999

lib/configfiles/bookworm.xml, lib/configfiles/bullseye.xml, lib/configfiles/focal.xml, lib/configfiles/jammy.xml, lib/configfiles/noble.xml
It seems that "worker_processes" auto feature is currently supported by all distributions supported by froxlor. This feautre seems older than i thought, so even old version should support it.
Automatic assignment should more optimize the nginx enviroment for more than 4 cpu cores or maybe even less cores.
This change was taken from default config of each distro, i have downloaded every version from WSL and tested the nginx.
Sources of the versions for each distro:
Ubuntu: https://packages.ubuntu.com/search?keywords=nginx
Debian bullseye: https://packages.debian.org/bullseye/nginx
Debian bookworm: https://packages.debian.org/bookworm/nginx
Nginx docs reference:
https://nginx.org/en/docs/ngx_core_module.html#worker_processes
=> Automatic assigment of "worker_processes" in nginx

templates/Froxlor/form/formfields.html.twig
Add |raw to the h5 in the template to fix the escaped HTML output for example on admin_updates.php with the 2.2 update.
Before: 
After:
- Make change
- See correctly formatted output
* Distribution: Debian 12
* Webserver: Nginx
* PHP: 8.3 FPM
* etc.etc.:
=> Fix escaped html in description on Froxlor update screen

lib/configfiles/noble.xml
Missing Package Installation on Ubuntu Noble 24.04 - proftpd-mod-wrap (Froxlor 2.20) #1271
Change installation script to
apt-get install proftpd-basic proftpd-mod-mysql proftpd-mod-crypto proftpd-mod-wrap
Fixes #1271 
* Webserver:
* PHP:
* etc.etc.:
=> Fix missing proftpd-mod-wrap installation

templates/Froxlor/settings/apcuinfo.html.twig
The width of the APCu Miss bar in the Hit/Miss graph on the APCu info page is calculated incorrectly, resulting in both bars always being the same width. This PR fixes that issue.
Before:
After:
1. Make change
2. See bars with correct width
* Distribution: Debian 12
* Webserver: Nginx
* PHP: 8.3 FPM
* etc.etc.:
=> Fix incorrect width of APCu Hit/Miss bar

admin_apcuinfo.php
The APCu memory usage percent is not correct, because it is calculated with mem_avail, not with the mem_size.
This can lead to values above 100%, which obviously does not make sense.
Before: 
After:
Make change, see correct percentage :)
* Distribution: Debian 12
* Webserver: Nginx
* PHP: 8.3 FPM
* etc.etc.:
=> Fix APCu memory usage percent
